language: csharp

sudo: enabled

os: osx
osx_image: xcode9.3

dotnet: 2.1.300

env:
  global:
    - ANDROID_SDK_PATH="/usr/local/share/android-sdk"
    - PATH=$ANDROID_SDK_PATH/platform-tools:$PATH

mono: latest

install:
  - dotnet tool install fake-cli -g

script:
  - ./install-xamarin-android-ios.sh
  - msbuild /t:Restore
  - msbuild
