language: csharp

os: osx
osx_image: xcode10

dotnet: 2.1.402
mono: 5.12.0

env:
  global:
    - ANDROID_COMPONENTS=build-tools-27.0.3,android-27,extra-android-support,extra-google-google_play_services,extra-google-m2repository,extra-android-m2repository
    - ANDROID_LICENSES=android-sdk-license-c81a61d9
    - MONO_ANDROID_VERSION=9.0.0-20
    - MONO_IOS_VERSION=12.2.0.26

install:
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-2/android-sdk-installer | bash /dev/stdin --install=$ANDROID_COMPONENTS --accept=$ANDROID_LICENSES
  - source ~/.android-sdk-installer/env
  - wget "https://dl.xamarin.com/MonoforAndroid/Mac/xamarin.android-${MONO_ANDROID_VERSION}.pkg"
  - sudo installer -pkg "xamarin.android-${MONO_ANDROID_VERSION}.pkg" -target /
  - wget https://dl.xamarin.com/MonoTouch/Mac/xamarin.ios-$MONO_IOS_VERSION.pkg
  - sudo installer -pkg "xamarin.ios-${MONO_IOS_VERSION}.pkg" -target /
  - /Library/Frameworks/Mono.framework/Commands/nuget restore solution-name.sln

script:
  - msbuild /p:Configuration=Release Twitchdeck.sln