language: csharp

os: osx
osx_image: xcode10

sudo: true

dotnet: 2.1.402

env:
  global:
    - ANDROID_SDK_PATH="/usr/local/share/android-sdk"
    - PATH=$ANDROID_SDK_PATH/platform-tools:$PATH

mono: latest

install:
  - dotnet tool install fake-cli -g

script:
  - sudo ./install-xamarin-android-ios.sh
  - msbuild /t:Restore
  - msbuild
